otherTextInformationFrames= {
# 'TALB':'Album/Movie/Show title',
 'TBPM':'BPM (beats per minute)',
 'TCOM':'Composer',
# 'TCON':'Content type',
 'TCOP':'Original Sound Copyright message',
 'TDEN':'Date of Encoding',
 'TDLY':'Playlist delay (msec)',
 'TDOR':'Date of Original Release',
 'TDRC':'Date of Recording',
 'TDRL':'Date of Release',
 'TDTG':'Date of Tagging',
 'TENC':'Encoded by (may contain copyright message, as well)',
 'TEXT':'Lyricist/Text writer',
 'TFLT':'File type',
 'TIPL':'Involved people list',
# 'TIT1':'Content group description',
# 'TIT2':'Title/songname/content description',
 'TIT3':'Subtitle/Description refinement',
 'TKEY':'Initial musical key signature',
 'TLAN':'Language code(s)',
 'TLEN':'Length (msec.)',
 'TMCL':'Musician credits list',
 'TMED':'Media type from which sound originated',
 'TMOO':'Mood',
 'TOAL':'Original album/movie/show title',
 'TOFN':'Original filename',
 'TOLY':'Original lyricist(s)/text writer(s)',
 'TOPE':'Original artist(s)/performer(s)',
 'TOWN':'File owner/licensee',
# 'TPE1':'Lead performer(s)/Soloist(s)',
 'TPE2':'Band/orchestra/accompaniment',
 'TPE3':'Conductor/performer refinement',
 'TPE4':'Interpreted, remixed, or otherwise modified by',
 'TPOS':'Part of a set (such as a multiple cd set)',
 'TPRO':'Produced notice (production copyright holder of original sound)',
 'TPUB':'Publisher',
# 'TRCK':'Track number/Position in set',
 'TRSN':'Internet radio station name',
 'TRSO':'Internet radio station owner',
 'TSOA':'Album sort order (sort key)',
 'TSOP':'Performer sort order (sort key)',
 'TSOT':'Title sort order (sort key)',
 'TSRC':'ISRC (International Standard Recording Code)',
 'TSSE':'Software/Hardware and settings used for encoding',
 'TSST':'Set subtitle'
 }

UnhandledFrameDict = {
 'AENC':'Audio encryption',
 'APIC':'Attached picture',
 'ASPI':'Audio seek point index',
# 'COMM':'Comments', ' this is handled.
 'COMR':'Commercial frame',
 'ENCR':'Encryption method registration',
 'EQU2':'Equalisation (2)',
 'ETCO':'Event timing codes',
 'GEOB':'General encapsulated object',
 'GRID':'Group identification registration',
 'LINK':'Linked information',
 'MCDI':'Music CD identifier (binary TOC)',
 'MLLT':'MPEG location lookup table',
 'OWNE':'Ownership frame',
 'PRIV':'Private frame intended for use by software producer',
 'PCNT':'Play counter',
 'POPM':'Popularimeter',
 'POSS':'Position synchronisation frame',
 'RBUF':'Recommended buffer size',
 'RVA2':'Relative volume adjustment (2)',
 'RVRB':'Reverb',
 'SEEK':'Seek frame for additional tags',
 'SIGN':'Signature frame',
 'SYLT':'Synchronised lyric/text',
 'SYTC':'Synchronised tempo codes',
 'TXXX':'User defined text information frame',
 'UFID':'Unique file identifier',
 'USER':'Terms of use',
 'USLT':'Unsynchronised lyric/text transcription',
 'WCOM':'Commercial information URL',
 'WCOP':'Copyright/Legal information URL',
 'WOAF':'Official audio file webpage URL',
 'WOAR':'Official artist/performer webpage URL',
 'WOAS':'Official audio source webpage URL',
 'WORS':'Official Internet radio station homepage URL',
 'WPAY':'Payment URL',
 'WPUB':'Publishers official webpage URL',
 'WXXX':'User defined URL link frame',
 'TXXX':'User defined frame'
}
